# Use root/example as user/password credentials
version: '3.1'

services:
#  app:
#    image: basketball_app
#    build: .
#    ports:
#      - 8082:8082
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/basketball?autoReconnect=true&useSSL=false
#    depends_on:
#      - db


  db:
    image: mysql:5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: basketball
    ports:
      - "3306:3306"

