spring:
  jpa:
    hibernate:
      ddl-auto: update
  graphql:
    graphiql:
      enabled: true

  datasource:
    username: root
    password: example
    url: jdbc:mysql://localhost:3306/basketball?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8082



