spring:
  jpa:
    hibernate:
      ddl-auto: update

  graphql:
    graphiql:
      enabled: true

  datasource:
    username: root
    password: example
    url: jdbc:mysql://localhost:3306/basketball

server:
  port: 8082